-- Minimal pre-V32 PostgreSQL contract for isolated scheduling integration tests.
-- No production connection or application .env is used.
CREATE TABLE course(course_code varchar(20) PRIMARY KEY, course_name varchar(200) NOT NULL, is_active boolean DEFAULT true);
CREATE TABLE school(school_id integer PRIMARY KEY, school_name text);
CREATE TABLE programme(programme_id integer PRIMARY KEY, school_id integer REFERENCES school, is_active boolean DEFAULT true);
CREATE TABLE programme_course(programme_course_id integer PRIMARY KEY, programme_id integer REFERENCES programme,
 course_code varchar(20) REFERENCES course, semester smallint, is_active boolean DEFAULT true);
CREATE TABLE student(computer_number varchar(15) PRIMARY KEY, full_name text NOT NULL);
CREATE TABLE student_registration(computer_number varchar(15) REFERENCES student,course_code varchar(15),academic_year varchar(9),semester smallint,
 PRIMARY KEY(computer_number,course_code,academic_year,semester));
CREATE TABLE venue(venue_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,venue_name text,building text,capacity integer NOT NULL);
CREATE TABLE exam_session(exam_session_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,course_code varchar(15) NOT NULL,
 exam_date date NOT NULL,start_time time NOT NULL,end_time time NOT NULL,academic_year varchar(9) NOT NULL,semester smallint NOT NULL,
 exam_type varchar(20) NOT NULL,status varchar(20) DEFAULT 'SCHEDULED',CHECK(end_time>start_time));
CREATE TABLE exam_venue(exam_session_id integer REFERENCES exam_session ON DELETE CASCADE,venue_id integer REFERENCES venue,
 PRIMARY KEY(exam_session_id,venue_id));
CREATE TABLE student_venue_allocation(computer_number varchar(15) REFERENCES student,exam_session_id integer REFERENCES exam_session,
 venue_id integer REFERENCES venue,PRIMARY KEY(computer_number,exam_session_id));
CREATE TABLE exam_session_programme_course(exam_session_id integer REFERENCES exam_session ON DELETE CASCADE,
 programme_course_id integer REFERENCES programme_course, PRIMARY KEY(exam_session_id,programme_course_id));
CREATE TABLE staff(staff_id integer PRIMARY KEY,account_status varchar(20));
CREATE TABLE role(role_id integer PRIMARY KEY,name varchar(50));
CREATE TABLE staff_role(staff_id integer REFERENCES staff,role_id integer REFERENCES role,PRIMARY KEY(staff_id,role_id));
CREATE TABLE invigilator_assignment(exam_session_id integer,venue_id integer,staff_id integer REFERENCES staff,
 assignment_status varchar(20) DEFAULT 'DRAFT',published_at timestamp,PRIMARY KEY(exam_session_id,venue_id,staff_id),
 FOREIGN KEY(exam_session_id,venue_id) REFERENCES exam_venue ON DELETE CASCADE);
CREATE TABLE attendance(exam_session_id integer REFERENCES exam_session);
CREATE TABLE incident(exam_session_id integer REFERENCES exam_session);
CREATE TABLE generated_report(exam_session_id integer REFERENCES exam_session);

CREATE TABLE course_lecturer(course_code varchar(15),staff_id integer REFERENCES staff,PRIMARY KEY(course_code,staff_id));
