-- Existing Supabase catalogs are preserved. Populate missing catalogs with
-- approved curriculum data and explicit exam mappings before assigning staff.
CREATE TABLE IF NOT EXISTS public.school (
    school_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_code varchar(30) NOT NULL UNIQUE,
    school_name varchar(200) NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.programme (
    programme_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id integer NOT NULL REFERENCES public.school(school_id),
    programme_code varchar(30) NOT NULL UNIQUE,
    programme_name varchar(200) NOT NULL,
    duration_years smallint NOT NULL CHECK (duration_years > 0),
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.course (
    course_code varchar(20) PRIMARY KEY,
    course_name varchar(200) NOT NULL,
    credit_hours integer,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.programme_course (
    programme_course_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_id integer NOT NULL REFERENCES public.programme(programme_id),
    course_code varchar(20) NOT NULL REFERENCES public.course(course_code),
    year_of_study smallint NOT NULL CHECK (year_of_study > 0),
    semester smallint NOT NULL CHECK (semester > 0),
    course_category varchar(30) NOT NULL DEFAULT 'COMPULSORY',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (programme_id, course_code, year_of_study, semester)
);

CREATE TABLE IF NOT EXISTS public.exam_session_programme_course (
    exam_session_id integer NOT NULL REFERENCES public.exam_session(exam_session_id) ON DELETE CASCADE,
    programme_course_id integer NOT NULL REFERENCES public.programme_course(programme_course_id),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (exam_session_id, programme_course_id)
);

CREATE INDEX IF NOT EXISTS idx_assignment_curriculum
    ON public.programme_course(programme_id, year_of_study, course_code, semester);
CREATE INDEX IF NOT EXISTS idx_assignment_curriculum_exam
    ON public.exam_session_programme_course(programme_course_id, exam_session_id);
