-- Apply after the existing Supabase academic catalog has been seeded.
-- PostgreSQL 15+ (NULLS NOT DISTINCT). Run the whole script in one transaction.
-- Preserves programme_course IDs, exam mappings, course ownership and seat allocations.
BEGIN;

-- Reject conflicting parent rows before moving any curriculum entries.
DO $$
BEGIN
    IF current_setting('server_version_num')::integer < 150000 THEN
        RAISE EXCEPTION 'V30 requires PostgreSQL 15 or newer';
    END IF;
    IF EXISTS (
        SELECT 1 FROM public.programme p
        JOIN public.school s ON s.school_id = p.school_id
        WHERE (p.programme_code = 'BCS' AND (s.school_code <> 'SNS' OR NOT p.is_active))
           OR (p.programme_code = 'BENG' AND (s.school_code <> 'ENG' OR NOT p.is_active))
    ) THEN
        RAISE EXCEPTION 'Existing BCS/BENG parent has the wrong school or is inactive; resolve before V30';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.major (
    major_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_id integer NOT NULL REFERENCES public.programme(programme_id),
    major_code varchar(30) NOT NULL UNIQUE,
    major_name varchar(200) NOT NULL,
    legacy_programme_id integer UNIQUE REFERENCES public.programme(programme_id),
    is_active boolean NOT NULL DEFAULT TRUE,
    UNIQUE (major_id, programme_id)
);

ALTER TABLE public.programme_course ADD COLUMN IF NOT EXISTS major_id integer;
ALTER TABLE public.programme_course ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT TRUE;

-- The same course/year/semester can occur in several majors of one programme.
DO $$
DECLARE old_constraint record;
BEGIN
    FOR old_constraint IN
        SELECT conname FROM pg_constraint
        WHERE conrelid = 'public.programme_course'::regclass AND contype = 'u'
          AND pg_get_constraintdef(oid) = 'UNIQUE (programme_id, course_code, year_of_study, semester)'
    LOOP
        EXECUTE format('ALTER TABLE public.programme_course DROP CONSTRAINT %I', old_constraint.conname);
    END LOOP;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.programme_course'::regclass AND conname = 'programme_course_major_unique') THEN
        ALTER TABLE public.programme_course ADD CONSTRAINT programme_course_major_unique
            UNIQUE NULLS NOT DISTINCT (programme_id, major_id, course_code, year_of_study, semester);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.programme_course'::regclass AND conname = 'programme_course_major_parent_fk') THEN
        ALTER TABLE public.programme_course ADD CONSTRAINT programme_course_major_parent_fk
            FOREIGN KEY (major_id, programme_id) REFERENCES public.major(major_id, programme_id);
    END IF;
END $$;

-- Confirmed grouping: Computer Science programme, three majors.
DO $$
BEGIN
    IF (SELECT count(*) FROM public.programme p JOIN public.school s ON s.school_id = p.school_id
        WHERE s.school_code = 'SNS' AND p.programme_code IN ('BCS-CS', 'BCS-SE', 'BCS-NIS')) <> 3 THEN
        RAISE EXCEPTION 'Expected the three existing BCS-CS, BCS-SE and BCS-NIS catalog entries under SNS';
    END IF;
END $$;

INSERT INTO public.programme (school_id, programme_code, programme_name, duration_years)
SELECT school_id, 'BCS', 'Bachelor of Computer Science', duration_years
FROM public.programme WHERE programme_code = 'BCS-CS'
ON CONFLICT (programme_code) DO NOTHING;

INSERT INTO public.major (programme_id, major_code, major_name, legacy_programme_id)
SELECT parent.programme_id, mapping.code, mapping.name, legacy.programme_id
FROM (VALUES
    ('BCS-CS', 'Computer Science'),
    ('BCS-SE', 'Software Engineering'),
    ('BCS-NIS', 'Networking and Information Security')
) AS mapping(code, name)
JOIN public.programme legacy ON legacy.programme_code = mapping.code
JOIN public.programme parent ON parent.programme_code = 'BCS' AND parent.school_id = legacy.school_id
ON CONFLICT (major_code) DO NOTHING;

-- Confirmed grouping: Engineering programme, three majors.
DO $$
BEGIN
    IF (SELECT count(*) FROM public.programme p JOIN public.school s ON s.school_id = p.school_id
        WHERE s.school_code = 'ENG' AND p.programme_code IN ('BENG-EE', 'BENG-CE', 'BENG-ME')) <> 3 THEN
        RAISE EXCEPTION 'Expected the three existing BENG-EE, BENG-CE and BENG-ME catalog entries under ENG';
    END IF;
END $$;

INSERT INTO public.programme (school_id, programme_code, programme_name, duration_years)
SELECT school_id, 'BENG', 'Bachelor of Engineering', duration_years
FROM public.programme WHERE programme_code = 'BENG-EE'
ON CONFLICT (programme_code) DO NOTHING;

INSERT INTO public.major (programme_id, major_code, major_name, legacy_programme_id)
SELECT parent.programme_id, mapping.code, mapping.name, legacy.programme_id
FROM (VALUES
    ('BENG-EE', 'Electrical and Electronic Engineering'),
    ('BENG-CE', 'Civil and Environmental Engineering'),
    ('BENG-ME', 'Mechanical Engineering')
) AS mapping(code, name)
JOIN public.programme legacy ON legacy.programme_code = mapping.code
JOIN public.programme parent ON parent.programme_code = 'BENG' AND parent.school_id = legacy.school_id
ON CONFLICT (major_code) DO NOTHING;

UPDATE public.programme_course pc
SET programme_id = m.programme_id, major_id = m.major_id, updated_at = CURRENT_TIMESTAMP
FROM public.major m
WHERE pc.programme_id = m.legacy_programme_id;

-- Preserve each student's known major when migrating normalized enrolments.
DO $$
BEGIN
    IF to_regclass('public.student_programme_enrolment') IS NOT NULL THEN
        ALTER TABLE public.student_programme_enrolment ADD COLUMN IF NOT EXISTS major_id integer;
        UPDATE public.student_programme_enrolment e
        SET programme_id = m.programme_id, major_id = m.major_id, updated_at = CURRENT_TIMESTAMP
        FROM public.major m WHERE e.programme_id = m.legacy_programme_id;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint
            WHERE conrelid = 'public.student_programme_enrolment'::regclass
              AND conname = 'student_enrolment_major_parent_fk') THEN
            ALTER TABLE public.student_programme_enrolment ADD CONSTRAINT student_enrolment_major_parent_fk
                FOREIGN KEY (major_id, programme_id) REFERENCES public.major(major_id, programme_id);
        END IF;
    END IF;
END $$;

-- Retain legacy rows for references/history, but remove them from active programme selectors.
UPDATE public.programme p SET is_active = FALSE, updated_at = CURRENT_TIMESTAMP
WHERE EXISTS (SELECT 1 FROM public.major m WHERE m.legacy_programme_id = p.programme_id);

CREATE INDEX IF NOT EXISTS idx_programme_course_major ON public.programme_course(programme_id, major_id, year_of_study);

COMMIT;
